[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run prisma:generate"]

[start]
cmd = "npx tsx src/scripts/ai-analysis-worker.ts"